# Generated by Django 3.1.2 on 2021-02-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcar',
            name='carimage',
            field=models.ImageField(upload_to='blogs/images'),
        ),
    ]
