# Generated by Django 3.1.2 on 2021-02-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20210227_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcar',
            name='carimage',
            field=models.ImageField(upload_to='newcarimages'),
        ),
    ]
