# Generated by Django 3.1.2 on 2021-02-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20210227_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcar',
            name='carimage',
            field=models.ImageField(upload_to='newcarimage'),
        ),
    ]
